### ISSUE TITLE
List of works to be done

### ISSUE THREAD

**Issue by shpingalet007** [pocketnetteam/pocketnet.gui#441]
# Why we need to do this
Effective work is only possible if the project is easy to maintain and develop. We are gradually reaching a point where there is a need to restructure the project and optimize it. This time we have to take into account the experience gained during the development process and create a project structure that will not require much modernization in the coming years.

# Plan of works
In this issue, I describe a rough plan of work to be done in the coming months. For convenience, it is divided into stages and arranged in order of importance.

## Stage 0 - Preparations
- [ ] **Chat separation** - Remove compiled [pocketnetteam/bastyon-chat](https://github.com/pocketnetteam/bastyon-chat) from **`/chat`** folder. It must be fetched on app build process.
- [ ] **Player separation** - Remove compiled [zanhesl/Peertube-Player](https://github.com/zanhesl/Peertube-Player) from **`/peertube`** folder. It must be fetched on app build process.
- [ ] **Proxy16 separation** - Divide **`/proxy16`** in a separate Proxy16 repository. It must be fetched on app build process.
- [ ] **Lint script** - Clean project from redundant empty lines and spaces. Replace tabulation symbols to 2/4 spaces. Add light version of lint to automate the process for developers. This will make merge conflicts easier.
- [ ] **LESS compilation** - Automize compilation of LESS stylesheets and remove their built versions. The work is already done, but still not accepted from https://github.com/pocketnetteam/pocketnet.gui/pull/390.

## Stage 1 - Project structure
- [ ] **Easier folders structure** - Review the project structure. Remove redundant files and folders. New structure must be oriented on Webpack, but at this stage we don't add it as it is difficult. [Example of nice structure](https://vuejs-templates.github.io/webpack/structure.html). As we are building the same project in Electron, Cordova and web apps, we need to design something hybrid.

## Stage 2 - Optimization of development
- [ ] **Start using import/export** - On this step, we don't radically remove all global vars, just preparing things for Webpack arrival. All globals will be liquidated on **STAGE 3**.
- [ ] **Remove modules from repository** - There are scripts as jQuery, Axios, Moment.js, etc. inside of `/js/vendor` and other folders. Our repository is based on NPM, so why not installing them and import when we need them? Yeah, some scripts were changed, but this is a separate story. With help of Git we can find the changes and separate them too. One by one...

## Stage 3 - Optimization of build process
- [ ] - **Webpack** - On this step we can without many issues accept Webpack.
- [ ] - **Remove global variables** - This must be stopped. It is not either not secure, it creates problems for developers. They can't understand what files depend on what. Even the IDEs in most cases can't make the development easier so they need to use classic file search.

# FAQ - Some questions answered
## Wait, why need to use Webpack? We have our custom!

First of all, Webpack was created by people who have an objective of simplifying the build process for everyone. Better to rely on them than writing our own. We wouldn't make it better than they already did.

Secondly, when project is using Webpack, developers doesn't need to think how to attach Babel, obfuscation, LESS compilation or any other extra functionality. They can be easily included in a few minutes. And what is important, Webpack is documented well, so any developer of the project can make changes in it to add some specific tasks.

## Can we use `require()` instead of `import/export`?

While `require()` is still supported, some big NPMs decided to stop support it. So, there is a trend on leaving it out. To not change the things after, let's move exclusively to `import/export` syntax on refactoring stages. Anyway, Webpack is handling out this for us.
