### ISSUE TITLE
Release 0.8.6 - List of works to be done

### ISSUE THREAD

**Issue by shpingalet007** [pocketnetteam/pocketnet.gui#484]
# Tasks to complete
### Small fixes
- [x] **`⬇️ merged`** #296
- [x] **`⬇️ merged`** #502
- [x] **`⬇️ merged`** #562
- [x] **`⬇️ merged`** #475
- **`🌀 delayed`** #496
- **`🌀 delayed`** #497
- **`🌀 delayed`** #507

### Features
- [x] **`⬇️ merged`** #498
- [x] **`⬇️ merged`** #463
- [x] **`⬇️ merged`** #570
- [x] **`⬇️ merged`** #567
- **`🌀 delayed`** #499
- **`🌀 delayed`** #464

**Comment by shpingalet007** [comment]
### Testing pre-release 1 (v0.7.80) - ea97158
- [ ] #463
- [ ] #464
- [ ] #499
- [ ] #296

**Comment by shpingalet007** [comment]
### Testing pre-release 3 (v0.7.80) - 780a703
- [ ] #502 
- [ ] #464
- [ ] #501

**Comment by shpingalet007** [comment]
### Setting release version to v0.7.90
Tor arrived from #445. Current master version now is v0.7.85. Adding +5 for this release features.

**Comment by shpingalet007** [comment]
### Removed from release #499

**Comment by shpingalet007** [comment]
### Removed from release #505. Early patched

**Comment by shpingalet007** [comment]
### Rebase `release` branch on `origin/master` - `pending`

**Comment by shpingalet007** [comment]
### Testing pre-release 6 (v0.7.97) - `pending`
- [ ] #463
- [ ] #499

**Comment by shpingalet007** [comment]
### Testing pre-release 6 (v0.7.97) - `d8e33bc`
- [ ] #463
- [ ] #499

**Comment by shpingalet007** [comment]
### Testing pre-release 7 (v0.8.2) - cf0ee04
- [ ] #499

**Comment by shpingalet007** [comment]
### Testing pre-release 8 (v0.8.X) - `pending`
- [ ] #499
- [ ] #463
- [ ] #502

**Comment by shpingalet007** [comment]
### Testing pre-release 8 (v0.8.X) - `pending`
- [ ] #499
- [ ] #463
- [ ] #502
- [ ] #517

**Comment by shpingalet007** [comment]
### Out of the flow changes made by @maxgithubprofile accepted
- [x] 0e49680 - #548 merged on invalid branch. Deployed on `release`
- [x] 8fb41fd - **satolist.js** patch

**Comment by shpingalet007** [comment]
### Testing pre-release 9 (v0.8.4) - cc4a164
- [ ] #548
- [ ] @maxgithubprofile patches

**Comment by shpingalet007** [comment]
### Out of the flow changes made by @maxgithubprofile accepted
- e2aa17d - #548 merged on invalid branch. Deployed on `release`
- e122f70 - **satolist.js** patch

**Comment by shpingalet007** [comment]
### Testing pre-release 8 (v0.8.3) - 843ffe1
- [ ] e2aa17d, e122f70 - Out of the flow changes
- [ ] #499
- [ ] #463
- [ ] #502
- [ ] #517

**Comment by shpingalet007** [comment]
### Branch `release` was rebased from 54b0e9b to 61b5f81. Fixed

**Comment by shpingalet007** [comment]
### Testing pre-release 11 (v0.8.4) - 54b0e9b
- [ ] 17b7f4c - Chat update from [bastyon-chat](https://github.com/pocketnetteam/bastyon-chat)
- [ ] 14f96ad - Mobile video player fixes and other things by @maxgithubprofile. Out of the flow

**Comment by shpingalet007** [comment]
### Rebase `release` branch on `origin/master` - bccd03e
- [ ] **`🚫 removed`** #517
- [ ] **`🚫 temporary removed`** #498

**Comment by shpingalet007** [comment]
### Testing pre-release 14 (v0.8.4) - `pending`
- [ ] #475
- [ ] #499
- [ ] #463

**Comment by shpingalet007** [comment]
### Testing pre-release 14 (v0.8.4) - 30f3297
- [ ] #475
- [ ] #499
- [ ] #463

**Comment by shpingalet007** [comment]
### Returned **`✅ accepted`** #498 on 83d2823

**Comment by shpingalet007** [comment]
### Testing pre-release 14 (v0.8.4) - `pending`
- [ ] #475
- [ ] #463

**Comment by shpingalet007** [comment]
### Testing pre-release 15 (v0.8.4) - 64759de
- [ ] #475
- [ ] #463

**Comment by shpingalet007** [comment]
### Testing pre-release 18 (v0.8.4) - 0513088
- [ ] #562
- [ ] #498
- [ ] #567
- [ ] #555
- [ ] **`🚫 removed`** #464

**Comment by shpingalet007** [comment]
### Testing pre-release 18 (v0.8.4) - `pending`
- [ ] #562
- [ ] #498
- [ ] #567
- [ ] #555
- [ ] **`🚫 removed`** #464
