### ISSUE TITLE
Next release - List of works to be done

### ISSUE THREAD

**Issue by shpingalet007** [pocketnetteam/pocketnet.gui#587]
# Tasks to complete

### Fixes
- [x] **`⬇️ merged, not tested, failed`** #583
- [x] **`⬇️ merged`** #545
- [x] **`⬇️ merged`** #580
- [x] **`⬇️ merged`** #497
- [x] **`⬇️ merged`** #636
- [x] **`⬇️ merged`** #463
- [x] **`⬇️ merged`** #507
- [x] **`⬇️ merged`** #597
- [x] **`⬇️ merged`** #607
- [x] **`⬇️ merged`** #622

### Features
- [x] **`⬇️ merged`** #589
- [x] **`⬇️ merged`** #565
- [x] **`⬇️ merged`** #543
- [x] **`⬇️ merged`** #610
- [x] **`⬇️ merged`** #592

### Refactoring
- [x] **`⬇️ merged`** #588
- [x] **`⬇️ merged`** #607

### Minor (#613)

- [x] Fix #462 bugs
- [x] Fix #583 crashing cordova app
- [x] New users added to testers list
- [x] Voice messages functionality allowed for public use
- [x] Chat updates (voice messages, peertube hints, other fixes)
- [x] New profiles added to confirmed list

**Comment by shpingalet007** [comment]
### Iteration 1 - 340c9c6
- [ ] #446
- [ ] #581
- [ ] #580
- [ ] #583
- [ ] #565
- [ ] #588
- [ ] #589

**Comment by shpingalet007** [comment]
### Testing iteration 2 - `pending`
- [ ] #573

**Comment by shpingalet007** [comment]
### Testing iteration 2 - fcd1d57
- [ ] #580
- [ ] #446
- [ ] #558

**Comment by shpingalet007** [comment]
### Testing iteration 2 - fcd1d57
- [ ] #580
- [ ] #446
- [ ] #558
- [ ] #582
- [ ] #592

**Comment by shpingalet007** [comment]
### Testing iteration 4 - 7f26b98
- [ ] #565
- [ ] Comment banner fixes and logging

**Comment by shpingalet007** [comment]
### Accepted #583 without tests on 0d3e522

**Comment by shpingalet007** [comment]
### Testing iteration 5 - f651c8d
- [ ] #446
- [ ] Comment banner fixes and logging on 8c850b2

**Comment by shpingalet007** [comment]
### Testing iteration 6 - 825d5ff
- [ ] Comment banner fixes
- [ ] #446

**Comment by shpingalet007** [comment]
### Testing iteration 7 - ba527b5
- [ ] Old download app banner removed on a7bf0cf
- [ ] #593

**Comment by shpingalet007** [comment]
### Testing iteration 8 - 926371a
- [ ] #588
- [ ] #597
- [ ] #581

**Comment by shpingalet007** [comment]
### Testing iteration 10 - 47c46bc
- [ ] #600

**Comment by shpingalet007** [comment]
### Testing iteration 10 - bc72200
- [ ] #597

**Comment by shpingalet007** [comment]
### Rebased `release` branch from 1c4f734 to a7bf0cf

**Comment by shpingalet007** [comment]
### Testing iteration 12 - 3cd79cf
- [ ] Update test users list on e4a14e3 and b951bc2
- [ ] Captcha removed from tests

**Comment by shpingalet007** [comment]
### Testing iteration 12 - 3cd79cf, 570adc4
- [ ] Update test users list on e4a14e3 and b951bc2
- [ ] Captcha removed from tests

**Comment by shpingalet007** [comment]
### Testing iteration 13 - f488732
- [ ] #607
- [ ] #601

**Comment by shpingalet007** [comment]
### Testing iteration 14 - 448417c
- [ ] ~~c353d35 Full screen chat mode~~
- [ ] ~~47770c4 Comment banner fixes~~
- [ ] #507
- [ ] #602
- [ ] #610
- [ ] #583 was breaking Cordova build. Fixed

### Testing iteration 15 - 4257f09
- [ ] #589
- [ ] #565

### Testing iteration 16 - ab98215
- [ ] #573

**Comment by shpingalet007** [comment]
### Released on 0.8.10
https://github.com/pocketnetteam/pocketnet.gui/releases/tag/v0.8.10
